version: "3"

services:

  keycloak:
    image: jboss/keycloak
    links:
      - keycloak-postgres:postgres
    expose:
      - "8080"
    ports:
      - "8080"
    volumes:
      - ./keycloak:/opt/jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=keycloak
      - "PROXY_ADDRESS_FORWARDING=true"
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=kc.lawandorder.ai
      - LETSENCRYPT_HOST=kc.lawandorder.ai
      - LETSENCRYPT_EMAIL=admin@lawandorder.ai

  keycloak-postgres:
    image: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak

